### create doctor queue // fixed doctor id for simplicity
POST http://localhost:8080/doctor-queues/629c93cae6509bc3a7b1aaf7
Content-Type: application/json

### create visit // random visit id
POST http://localhost:8080/his/visits
Content-Type: application/json

{
  "name": "Shane",
  "gender": "ABC",
  "age": 123
}

### submit assessment to visit // will push visit the doctor queue (with fixed id)
PUT http://localhost:8080/his/visits/62a5c0745679ad14ce97e763/assessment
Content-Type: application/json

{
  "comment": "Very Goooood",
  "painScore": 999
}
